version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/php/Dockerfile
    container_name: backend_app
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    networks:
      - appnet
    ports:
      - "8000:80"
    command: >
      sh -c "chown -R www-data:www-data /var/www/html &&
            chmod -R 775 /var/www/html/storage /var/www/html/bootstrap/cache &&
            apache2-foreground"

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    container_name: frontend_app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "4200:4200"
    networks:
      - appnet
    command: ["npm", "start"]

  db:
    image: mariadb:10.5
    container_name: db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - appnet

volumes:
  dbdata:

networks:
  appnet:
    driver: bridge
